[env:mkrwifi1010]
platform = atmelsam
board = mkrwifi1010
framework = arduino
lib_deps =
    arduino-libraries/WiFiNINA
    ArduinoOTA
monitor_speed = 115200
build_flags = 
	-Wno-unknown-pragmas
	-I include
	-I lib
	-D MKR1010